# Generated by Django 3.1.5 on 2021-02-17 17:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_name', models.CharField(help_text='enter title of the homework', max_length=200)),
                ('text_homework', models.CharField(help_text='Insert the text of homework', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='enter title of the subject', max_length=200)),
                ('description', models.CharField(help_text='enter the description of the subject', max_length=1000)),
                ('homework_list', models.ManyToManyField(to='univ.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_count', models.IntegerField(default=0)),
                ('subjects', models.ManyToManyField(to='univ.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='UnivInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular univ', primary_key=True, serialize=False)),
                ('univ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.univ')),
            ],
        ),
        migrations.AddField(
            model_name='univ',
            name='years',
            field=models.ManyToManyField(to='univ.Year'),
        ),
    ]
