# Generated by Django 3.1.5 on 2021-02-24 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_name', models.CharField(max_length=200)),
                ('text_homework', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['homework_name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('homework_list', models.ManyToManyField(to='univ.Homework')),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['univ_name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_count', models.CharField(max_length=200)),
                ('year_introduction', models.CharField(max_length=200, null=True)),
                ('subjects', models.ManyToManyField(to='univ.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='YearInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular year', primary_key=True, serialize=False)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.year')),
            ],
        ),
        migrations.CreateModel(
            name='UnivInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular univ', primary_key=True, serialize=False)),
                ('univ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.univ')),
            ],
        ),
        migrations.AddField(
            model_name='univ',
            name='years',
            field=models.ManyToManyField(to='univ.Year'),
        ),
        migrations.CreateModel(
            name='SubjectInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular subject', primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.subject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular homework', primary_key=True, serialize=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.homework')),
            ],
        ),
    ]
