# Generated by Django 3.1.5 on 2021-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='text_homework',
            field=models.TextField(blank=True),
        ),
    ]
