# Generated by Django 3.1.5 on 2021-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0002_auto_20210217_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=200),
        ),
    ]
