# Generated by Django 3.1.5 on 2021-02-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0003_auto_20210217_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year_count',
            field=models.CharField(max_length=200),
        ),
    ]
