# Generated by Django 3.1.5 on 2021-02-17 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0004_auto_20210217_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='univ',
            options={'ordering': ['univ_name']},
        ),
        migrations.CreateModel(
            name='YearInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular year', primary_key=True, serialize=False)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.year')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular subject', primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.subject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular homework', primary_key=True, serialize=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='univ.homework')),
            ],
        ),
    ]
