# Generated by Django 3.1.5 on 2021-02-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ', '0005_auto_20210217_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['homework_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name']},
        ),
    ]
